name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: recommendationmodel  # Set this to the name of your Azure Web App
  PYTHON_VERSION: '3.12.6'              # Adjust this to your Python version if different

on:
  push:
    branches: [ "main" ]  # Adjust the branch as needed
  workflow_dispatch:  # Allows manual trigger of the workflow

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v3.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create virtual environment
        run: python -m venv venv

      - name: Activate virtual environment and install dependencies
        run: |
          if [ $RUNNER_OS == 'Windows' ]; then 
            venv\Scripts\activate; 
          else 
            source venv/bin/activate; 
          fi
          pip install -r requirements.txt
